export interface PromptTemplate {
  name: string;
  render: (transcript: string) => string;
}

const prompts: Record<string, PromptTemplate> = {
  summary: {
    name: "Summary",
    render: (transcript) => `# Conversation Summary\n\n${transcript}\n\n— Generated by ChatKit` ,
  },
  compliance: {
    name: "Compliance",
    render: (transcript) => `## Compliance Review\n\nKey findings:\n${transcript}`,
  },
};

export function getReportPrompt(format: string): PromptTemplate {
  return prompts[format] ?? prompts.summary;
}
